version: "3.7"
services:

    agile:
        container_name: agile
        hostname: agile
        labels:
            description: Agile Data Science 2.0
            name: agile
        tty: true
        image: rjurney/agile_data_science:latest
        restart: on-failure
        user: root
        environment:
            JUPYTER_ENABLE_LAB: "yes"
            GRANT_SUDO: "yes"
            JUPYTER_ALLOW_INSECURE_WRITES: "true"
        depends_on:
            - elastic
            - mongo
            - mongo-express
        ports:
            - "8888:8888"
            - "5001:5000" #5001 por conflicto por MacOS
            - "8080:8080"
            - "5050:5050"
        volumes:
            - ./:/home/jovyan
            - ./scripts:/scripts
        command: >
            pip install kafka-python pymongo
            bash -c "/scripts/start-spark-cluster.sh && start-notebook.sh"
        networks:
            - agile_net

    elastic:
        container_name: elastic
        hostname: elastic
        labels:
            description: Agile Data Science 2.0 Elastic
            name: elastic
        tty: True
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
        restart: always
        environment:
            cluster.name: "es-docker"
            discovery.type: single-node
            node.name: "elastic"
            ES_JAVA_OPTS: "-Xms1024m -Xmx1024m"
        ports:
            - "9200:9200"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - elastic_data:/usr/share/elasticsearch/data
            - ./logs:/usr/share/elasticsearch/logs
        networks:
            - agile_net

    mongo:
        container_name: mongo
        hostname: mongo
        labels:
            description: Agile Data Science 2.0 MongoDB
            name: mongo
        image: mongo:5.0.3
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
        networks:
            - agile_net

    mongo-express:
        container_name: mongo-express
        hostname: mongo-express
        labels:
            description: Agile Data Science 2.0 Mongo Express
            name: mongo-express
        image: mongo-express:0.54.0
        depends_on:
            - mongo
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
        networks:
            - agile_net

    zookeeper:
        container_name: zookeeper
        hostname: zookeeper
        labels:
            description: Agile Data Science 2.0 ZooKeeper
            name: zookeeper
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        networks:
            - agile_net

    kafka:
        container_name: kafka
        hostname: kafka
        labels:
            description: Agile Data Science 2.0 Kafka
            name: kafka
        image: wurstmeister/kafka:latest
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        networks:
            - agile_net
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    elastic_data:
    mongo_data:

networks:
    agile_net:
        name: agile_net
        driver: bridge
    
    # airflow_net:
    #     name: airflow_net
    #     driver: bridge